[build]
  command = "astro build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  directory = "netlify/functions/"

[functions."send-emails"]
  schedule = "@weekly"

[context.production]
  environment = { YOUR_RSS_FEED_URL = "/rss" }